#!/bin/bash -e
USER=admin

readonly TARGET_HOST=club-spa@192.168.205.40
readonly TARGET_PATH=/home/club-spa/Documents/ClubSpa/
readonly SOURCE_PATH=/Users/mystic/RiderProjects/ClubSpa/

dotnet publish --runtime linux-arm64 -c Debug
rsync -a -P ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}